backend:
  name: github
  repo: srtee/srtee.github.io
  base_url: https://sveltia-cms-auth.shernren.workers.dev/
  branch: main # branch to update
media_folder: "img/uploads"
collections:
  - name: "posts" # /admin/collections/blog
    label: "Posts" # UI
    folder: "_posts" # folder path
    create: true # let users create new docos
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # filename template
    fields: # front matter fields
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "_pages/about.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Profile", name: "profile", widget: "hidden"}
          - {label: "News", name: "news", widget: "boolean"}
          - {label: "Selected Papers", name: "selected_papers", widget: "boolean"}
          - {label: "Social", name: "social", widget: "boolean"}
          - {label: "Body", name: "body", widget: "markdown"}
